# Generated by Django 3.2.4 on 2021-07-22 18:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=120)),
                ('usuario', models.CharField(default='', max_length=20)),
                ('mail', models.CharField(max_length=100)),
                ('pasw', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahora', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('A', 'Alta'), ('B', 'Baja')], default='A', max_length=8)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
            options={
                'ordering': ('-fechahora',),
            },
        ),
    ]
