# Generated by Django 3.2.4 on 2021-07-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=300)),
                ('user', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
